In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [3]:
data = px.data.gapminder()
data.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [27]:
temp = data[data['year']==2007].sample(30)

In [19]:
px.scatter(data,x='lifeExp',y='pop',color='country',size='iso_num')

In [28]:
px.scatter(temp,x='lifeExp',y='pop',color='country',size='iso_num')

In [36]:
px.scatter(data,x='lifeExp',y='gdpPercap',color='continent',size='pop',
           size_max=50,range_x=[0,85],
           animation_frame='year',animation_group='country')

In [44]:
df = data[data['country'] =='India']

In [52]:
px.line(df,x='year',y='pop',markers='o')

In [79]:
temp_df = data[data['country'].isin(['India','United States','China'])].pivot(index='year',columns='country',values='lifeExp')
temp_df

country     China   India  United States
year
1952     44.00000  37.373         68.440
1957     50.54896  40.249         69.490
1962     44.50136  43.605         70.210
1967     58.38112  47.193         70.760
1972     63.11888  50.651         71.340
1977     63.96736  54.208         73.380
1982     65.52500  56.596         74.650
1987     67.27400  58.553         75.020
1992     68.69000  60.223         76.090
1997     70.42600  61.765         76.810
2002     72.02800  62.879         77.310
2007     72.96100  64.698         78.242

In [81]:
px.line(temp_df,x=temp_df.index,y=temp_df.columns)

In [82]:
temp_df = data[data['country'].isin(['India','United States','China'])].pivot(index='year',columns='country',values='gdpPercap')
temp_df

country        China        India  United States
year
1952      400.448611   546.565749    13990.48208
1957      575.987001   590.061996    14847.12712
1962      487.674018   658.347151    16173.14586
1967      612.705693   700.770611    19530.36557
1972      676.900092   724.032527    21806.03594
1977      741.237470   813.337323    24072.63213
1982      962.421381   855.723538    25009.55914
1987     1378.904018   976.512676    29884.35041
1992     1655.784158  1164.406809    32003.93224
1997     2289.234136  1458.817442    35767.43303
2002     3119.280896  1746.769454    39097.09955
2007     4959.114854  2452.210407    42951.65309

In [83]:
px.bar(temp_df,x=temp_df.index,y=temp_df.columns)

In [86]:
px.bar(temp_df,x=temp_df.index,y=temp_df.columns,barmode='group',text_auto=True,log_y=True)

In [99]:
df_1 = data[data['year']==2007]
px.bar(df_1,x='continent',y='pop',color='continent')

In [106]:
df_1 = data
px.bar(df_1,x='continent',y='pop',color='continent',animation_frame='year',animation_group='country',range_y=[0,4000000000])

In [112]:
df= data[(data['continent']=='Europe')&(data['year']==2007)]
px.pie(df,values='pop',names='country')

In [8]:
px.sunburst(data,path =['continent','country'],names='country',color='lifeExp')